name: CI

on: [push]

jobs:
  buikd:
    name: Build on node 10 and ubuntu-latest
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 10
      uses: actions/setup-node@v1
      with:
        version: 10

    - name: npm install and build
      run: |
        npm install
        npm run build --prod --if-present
        
    - name: Deploiement ssh
      uses: appleboy/scp-action@master
      env:
        HOST: 5.196.71.146
        PORT: 22
        USERNAME: ${{ secrets.FTP_USERNAME }}
        PASSWORD: ${{ secrets.FTP_PASSWORD }}
        SOURCE: dist/*
        TARGET: /opt/zthulj/
